/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinarRouteImport } from './routes/minar'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as AprendeIndexRouteImport } from './routes/aprende.index'
import { Route as AprendeSlugRouteImport } from './routes/aprende.$slug'
import { Route as AprendeQuizRouteImport } from './routes/aprende.quiz'
import { Route as AprendeTestRouteImport } from './routes/aprende.test'
import { Route as DiccionarioIndexRouteImport } from './routes/diccionario.index'
import { Route as DiccionarioSlugRouteImport } from './routes/diccionario.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinarRoute = MinarRouteImport.update({
  id: '/minar',
  path: '/minar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendeIndexRoute = AprendeIndexRouteImport.update({
  id: '/aprende/',
  path: '/aprende/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendeSlugRoute = AprendeSlugRouteImport.update({
  id: '/aprende/$slug',
  path: '/aprende/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendeQuizRoute = AprendeQuizRouteImport.update({
  id: '/aprende/quiz',
  path: '/aprende/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendeTestRoute = AprendeTestRouteImport.update({
  id: '/aprende/test',
  path: '/aprende/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DiccionarioIndexRoute = DiccionarioIndexRouteImport.update({
  id: '/diccionario/',
  path: '/diccionario/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiccionarioSlugRoute = DiccionarioSlugRouteImport.update({
  id: '/diccionario/$slug',
  path: '/diccionario/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minar': typeof MinarRoute
  '/privacidad': typeof PrivacidadRoute
  '/aprende/$slug': typeof AprendeSlugRoute
  '/aprende/quiz': typeof AprendeQuizRoute
  '/aprende/test': typeof AprendeTestRoute
  '/diccionario/$slug': typeof DiccionarioSlugRoute
  '/aprende/': typeof AprendeIndexRoute
  '/diccionario/': typeof DiccionarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minar': typeof MinarRoute
  '/privacidad': typeof PrivacidadRoute
  '/aprende/$slug': typeof AprendeSlugRoute
  '/aprende/quiz': typeof AprendeQuizRoute
  '/aprende/test': typeof AprendeTestRoute
  '/diccionario/$slug': typeof DiccionarioSlugRoute
  '/aprende': typeof AprendeIndexRoute
  '/diccionario': typeof DiccionarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minar': typeof MinarRoute
  '/privacidad': typeof PrivacidadRoute
  '/aprende/$slug': typeof AprendeSlugRoute
  '/aprende/quiz': typeof AprendeQuizRoute
  '/aprende/test': typeof AprendeTestRoute
  '/diccionario/$slug': typeof DiccionarioSlugRoute
  '/aprende/': typeof AprendeIndexRoute
  '/diccionario/': typeof DiccionarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/minar'
    | '/privacidad'
    | '/aprende/$slug'
    | '/aprende/quiz'
    | '/aprende/test'
    | '/diccionario/$slug'
    | '/aprende/'
    | '/diccionario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/minar'
    | '/privacidad'
    | '/aprende/$slug'
    | '/aprende/quiz'
    | '/aprende/test'
    | '/diccionario/$slug'
    | '/aprende'
    | '/diccionario'
  id:
    | '__root__'
    | '/'
    | '/minar'
    | '/privacidad'
    | '/aprende/$slug'
    | '/aprende/quiz'
    | '/aprende/test'
    | '/diccionario/$slug'
    | '/aprende/'
    | '/diccionario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinarRoute: typeof MinarRoute
  PrivacidadRoute: typeof PrivacidadRoute
  AprendeSlugRoute: typeof AprendeSlugRoute
  AprendeQuizRoute: typeof AprendeQuizRoute
  AprendeTestRoute: typeof AprendeTestRoute
  DiccionarioSlugRoute: typeof DiccionarioSlugRoute
  AprendeIndexRoute: typeof AprendeIndexRoute
  DiccionarioIndexRoute: typeof DiccionarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minar': {
      id: '/minar'
      path: '/minar'
      fullPath: '/minar'
      preLoaderRoute: typeof MinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprende/': {
      id: '/aprende/'
      path: '/aprende'
      fullPath: '/aprende/'
      preLoaderRoute: typeof AprendeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprende/$slug': {
      id: '/aprende/$slug'
      path: '/aprende/$slug'
      fullPath: '/aprende/$slug'
      preLoaderRoute: typeof AprendeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprende/quiz': {
      id: '/aprende/quiz'
      path: '/aprende/quiz'
      fullPath: '/aprende/quiz'
      preLoaderRoute: typeof AprendeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprende/test': {
      id: '/aprende/test'
      path: '/aprende/test'
      fullPath: '/aprende/test'
      preLoaderRoute: typeof AprendeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diccionario/': {
      id: '/diccionario/'
      path: '/diccionario'
      fullPath: '/diccionario/'
      preLoaderRoute: typeof DiccionarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diccionario/$slug': {
      id: '/diccionario/$slug'
      path: '/diccionario/$slug'
      fullPath: '/diccionario/$slug'
      preLoaderRoute: typeof DiccionarioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinarRoute: MinarRoute,
  PrivacidadRoute: PrivacidadRoute,
  AprendeSlugRoute: AprendeSlugRoute,
  AprendeQuizRoute: AprendeQuizRoute,
  AprendeTestRoute: AprendeTestRoute,
  DiccionarioSlugRoute: DiccionarioSlugRoute,
  AprendeIndexRoute: AprendeIndexRoute,
  DiccionarioIndexRoute: DiccionarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
