/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as DiccionarioIndexRouteImport } from './routes/diccionario.index'
import { Route as DiccionarioSlugRouteImport } from './routes/diccionario.$slug'
import { Route as Mining101IndexRouteImport } from './routes/mining-101.index'
import { Route as Mining101SlugRouteImport } from './routes/mining-101.$slug'
import { Route as Mining101QuizRouteImport } from './routes/mining-101.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const DiccionarioIndexRoute = DiccionarioIndexRouteImport.update({
  id: '/diccionario/',
  path: '/diccionario/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiccionarioSlugRoute = DiccionarioSlugRouteImport.update({
  id: '/diccionario/$slug',
  path: '/diccionario/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Mining101IndexRoute = Mining101IndexRouteImport.update({
  id: '/mining-101/',
  path: '/mining-101/',
  getParentRoute: () => rootRouteImport,
} as any)
const Mining101SlugRoute = Mining101SlugRouteImport.update({
  id: '/mining-101/$slug',
  path: '/mining-101/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Mining101QuizRoute = Mining101QuizRouteImport.update({
  id: '/mining-101/quiz',
  path: '/mining-101/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/privacidad': typeof PrivacidadRoute
  '/diccionario/$slug': typeof DiccionarioSlugRoute
  '/mining-101/$slug': typeof Mining101SlugRoute
  '/mining-101/quiz': typeof Mining101QuizRoute
  '/diccionario/': typeof DiccionarioIndexRoute
  '/mining-101/': typeof Mining101IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/privacidad': typeof PrivacidadRoute
  '/diccionario/$slug': typeof DiccionarioSlugRoute
  '/mining-101/$slug': typeof Mining101SlugRoute
  '/mining-101/quiz': typeof Mining101QuizRoute
  '/diccionario': typeof DiccionarioIndexRoute
  '/mining-101': typeof Mining101IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/privacidad': typeof PrivacidadRoute
  '/diccionario/$slug': typeof DiccionarioSlugRoute
  '/mining-101/$slug': typeof Mining101SlugRoute
  '/mining-101/quiz': typeof Mining101QuizRoute
  '/diccionario/': typeof DiccionarioIndexRoute
  '/mining-101/': typeof Mining101IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/privacidad'
    | '/diccionario/$slug'
    | '/mining-101/$slug'
    | '/mining-101/quiz'
    | '/diccionario/'
    | '/mining-101/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/privacidad'
    | '/diccionario/$slug'
    | '/mining-101/$slug'
    | '/mining-101/quiz'
    | '/diccionario'
    | '/mining-101'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/privacidad'
    | '/diccionario/$slug'
    | '/mining-101/$slug'
    | '/mining-101/quiz'
    | '/diccionario/'
    | '/mining-101/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  DiccionarioSlugRoute: typeof DiccionarioSlugRoute
  Mining101SlugRoute: typeof Mining101SlugRoute
  Mining101QuizRoute: typeof Mining101QuizRoute
  DiccionarioIndexRoute: typeof DiccionarioIndexRoute
  Mining101IndexRoute: typeof Mining101IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diccionario/': {
      id: '/diccionario/'
      path: '/diccionario'
      fullPath: '/diccionario/'
      preLoaderRoute: typeof DiccionarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diccionario/$slug': {
      id: '/diccionario/$slug'
      path: '/diccionario/$slug'
      fullPath: '/diccionario/$slug'
      preLoaderRoute: typeof DiccionarioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining-101/': {
      id: '/mining-101/'
      path: '/mining-101'
      fullPath: '/mining-101/'
      preLoaderRoute: typeof Mining101IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining-101/$slug': {
      id: '/mining-101/$slug'
      path: '/mining-101/$slug'
      fullPath: '/mining-101/$slug'
      preLoaderRoute: typeof Mining101SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining-101/quiz': {
      id: '/mining-101/quiz'
      path: '/mining-101/quiz'
      fullPath: '/mining-101/quiz'
      preLoaderRoute: typeof Mining101QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  PrivacidadRoute: PrivacidadRoute,
  DiccionarioSlugRoute: DiccionarioSlugRoute,
  Mining101SlugRoute: Mining101SlugRoute,
  Mining101QuizRoute: Mining101QuizRoute,
  DiccionarioIndexRoute: DiccionarioIndexRoute,
  Mining101IndexRoute: Mining101IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
